- hosts: terraform-ansible
  tasks:
  - name: Criando Arquivo
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Ajuste feito com Ansible</h1>
  - name: Criando Servidor
    shell: "nohup busybox httpd -f -p 8080 &"