---
- name: Install Oracle XE on Red Hat 9
  hosts: srv_oracle
  become: yes
  gather_facts: yes
  tasks:
    - name: Install dependencies
      yum:
        name:
          - wget
          - gcc
          - make
        state: present

    - name: Download Oracle XE RPM package
      get_url:
        url: curl -o oracle-database-preinstall-21c-1.0-1.el7.x86_64.rpm https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-database-preinstall-21c-1.0-1.el7.x86_64.rpm
        dest: /tmp/oracle-database-xe-19c-1.0-1.x86_64.rpm
        headers:
          Cookie: "oraclelicense=accept-securebackup-cookie"
      register: download_oracle_xe

    - name: Install Oracle XE RPM
      yum:
        name: /tmp/oracle-database-xe-19c-1.0-1.x86_64.rpm
        state: present
      when: download_oracle_xe.changed

    - name: Configure Oracle XE database
      command: /etc/init.d/oracledb_ORCLCDB configure
      args:
        creates: /etc/oratab

    - name: Ensure Oracle XE is running
      service:
        name: oracle-xe-19c
        state: started
        enabled: yes

    - name: Set Oracle Environment Variables
      lineinfile:
        path: ~/.bash_profile
        regexp: '^export\s+ORACLE_HOME'
        line: 'export ORACLE_HOME=/opt/oracle/product/19c/dbhome_1'

    - name: Reload the bash profile
      shell: source ~/.bash_profile