---
- name: Executar script SQL no Oracle Autonomous Database
  hosts: oracle_autonomous_db
  tasks:
    - name: Copiar o script SQL para o host remoto
      ansible.builtin.copy:
        src: /home/fransoar/FRAN/myself/OCI/FRAN_DB/ansible/criar_user.sql
        dest: /tmp/criar_user.sql

    - name: Executar script SQL no banco de dados via sqlplus
      ansible.builtin.shell: |
        sqlplus -S 'admin/As(1!3#wEsqAwA1!qW8*aQ'@{{ tns_alias }} @/tmp/criar_user.sql
      args:
        executable: /bin/bash
      register: sql_output

    - name: Mostrar o output do SQL
      debug:
        var: sql_output.stdout

    - name: Remover o script SQL do host remoto
      ansible.builtin.file:
        path: /tmp/criar_user.sql
        state: absent